### ISSUE TITLE
Ability to branch content

### ISSUE THREAD

**Issue by dave-calleja** [datocms/product-roadmap#52] opened 2018-06-12 13:22 UTC
Would be useful to (similar to git), be able to branch content and merge when required. Each user could have their own branch and merge when they are done with their feature.

**Comment by Convincible** [comment] 2018-06-18 21:47
The Draft/Published system goes a long way toward solving the use cases here

**Comment by stefanoverna** [comment] 2019-07-23 14:22
Duplicate of https://github.com/datocms/product-roadmap/issues/121

**Closed by stefanoverna** 2019-07-23 14:22 UTC
Labels: type: collaboration
