### ISSUE TITLE
Slack incoming webhook requires payload

### ISSUE THREAD

**Issue by lapidus** [datocms/product-roadmap#77] opened 2018-08-19 04:42 UTC
Pining a default Slack Incoming Webhook results in this error: `missing_text_or_fallback_or_attachments`.

Would be nice if the "add webhook" came with a way to customize the body so that one could add `payload={text: "Text-for-hook"}`.

**Comment by stefanoverna** [comment] 2019-07-23 14:14
Duplicate of https://github.com/datocms/product-roadmap/issues/168

**Closed by stefanoverna** 2019-07-23 14:14 UTC
Labels: type: integrations
